---
apiVersion: v1
kind: Namespace
metadata:
  name: highheath
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: highheath
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions
  namespace: highheath
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions
  namespace: highheath
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-actions
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: highheath
